# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-10-26 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import tweets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=160, validators=[tweets.models.validate_content]),
        ),
    ]
